# Generated by Django 5.2.5 on 2025-09-29 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DASTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DAST Scan', max_length=200, verbose_name='Nama Scan')),
                ('target_url', models.URLField(max_length=500, verbose_name='Target URL')),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('api', 'API Scan'), ('crawl', 'Crawl Only')], default='full', max_length=20, verbose_name='Tipe Scan')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Scan')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('pending', '🟡 Pending'), ('running', '🟠 Running'), ('completed', '🟢 Completed'), ('failed', '🔴 Failed'), ('canceled', '⚫ Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='Hasil Scan')),
                ('vulnerabilities_found', models.IntegerField(default=0, verbose_name='Total Vulnerabilitas')),
                ('high_vulnerabilities', models.IntegerField(default=0, verbose_name='Risiko Tinggi')),
                ('medium_vulnerabilities', models.IntegerField(default=0, verbose_name='Risiko Sedang')),
                ('low_vulnerabilities', models.IntegerField(default=0, verbose_name='Risiko Rendah')),
                ('informational_vulnerabilities', models.IntegerField(default=0, verbose_name='Informasional')),
                ('scan_duration', models.DurationField(blank=True, null=True, verbose_name='Durasi Scan')),
                ('pages_crawled', models.IntegerField(default=0, verbose_name='Halaman Di-crawl')),
                ('requests_made', models.IntegerField(default=0, verbose_name='Request Dibuat')),
                ('scan_config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Konfigurasi Scan')),
                ('active', models.BooleanField(default=True, verbose_name='Scan Aktif')),
                ('scheduled', models.BooleanField(default=False, verbose_name='Scan Terjadwal')),
                ('jenkins_build_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nomor Build Jenkins')),
                ('json_report_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Path Laporan JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('ai_recommendations', models.JSONField(blank=True, help_text='Rekomendasi keamanan yang dihasilkan oleh AI', null=True, verbose_name='Rekomendasi AI')),
                ('ai_analysis_status', models.CharField(choices=[('pending', '🟡 Menunggu Analisis'), ('processing', '🟠 Sedang Dianalisis'), ('completed', '🟢 Analisis Selesai'), ('failed', '🔴 Analisis Gagal')], default='pending', max_length=20, verbose_name='Status Analisis AI')),
                ('ai_analysis_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Analisis AI')),
                ('report_token', models.CharField(blank=True, default='', help_text='Token untuk akses aman ke laporan AI', max_length=100, verbose_name='Token Laporan')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dast_scans', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Scan')),
            ],
            options={
                'verbose_name': 'DAST Scan',
                'verbose_name_plural': 'DAST Scans',
                'ordering': ['-scan_date'],
                'permissions': [('view_own_dastscan', 'Can view own DAST scans only'), ('view_all_dastscan', 'Can view all DAST scans')],
            },
        ),
    ]
