# Generated by Django 5.2.5 on 2025-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('service', models.CharField(blank=True, choices=[('VAPT', 'VAPT (Vulnerability Assemnt & Penetration'), ('RedTeam', 'Red Teaming Expert'), ('SAST', 'SAST (Static Applicatiuon Security Testing)'), ('DAST', 'DAST (Dynamic Application Security Testing)'), ('SOC', '24/7 Security Operation'), ('Monitoring', 'Monitoring & Incident Response'), ('Consulting', 'Cybersecurity Consulting'), ('Security Awarenes', 'Security Awarenes'), ('Breach Investigasi', 'Breach Investigasi'), ('DarkWeb', 'DarkWeb Monitoring'), ('other', 'Other')], max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='message_mes_status_03314b_idx'), models.Index(fields=['priority', 'created_at'], name='message_mes_priorit_ca2ec8_idx')],
            },
        ),
    ]
