# Generated by Django 5.2.5 on 2025-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('nama_website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aplikasi', models.CharField(max_length=255)),
                ('versi_aplikasi', models.CharField(max_length=50)),
                ('hasil_scan', models.TextField()),
                ('tanggal_scan', models.DateTimeField(auto_now_add=True)),
                ('link_hasil_scan', models.TextField()),
            ],
        ),
    ]
